# Generated by Django 6.1.1 on 2026-09-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_options_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="course",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
            ),
        ),
    ]
